# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kink < Formula
  desc "KinK is a helper CLI that facilitates to manage KinD clusters as Kubernetes pods. Designed to ease clusters up for fast testing with batteries included in mind."
  homepage "https://github.com/trendyol"
  version "0.1.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Trendyol/kink/releases/download/v0.1.0/kink_0.1.0_Darwin-x86_64.tar.gz"
      sha256 "e191a64b59008988181c875e504f1cc76de4b959d74c8dca9e4c22c383e161cd"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Trendyol/kink/releases/download/v0.1.0/kink_0.1.0_Linux-x86_64.tar.gz"
      sha256 "3136d6ed4d54802cce2641db905f11483da8fd1362d9109462bbead021644a67"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "kink"
    bash_completion.install "completions/kink.bash" => "kink"
    zsh_completion.install "completions/kink.zsh" => "_kink"
    fish_completion.install "completions/kink.fish"
  end

  test do
    system "#{bin}/kink version"
  end
end
