# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kink < Formula
  desc "KinK is a helper CLI that facilitates to manage KinD clusters as Kubernetes pods. Designed to ease clusters up for fast testing with batteries included in mind."
  homepage "https://github.com/trendyol"
  version "0.1.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Trendyol/kink/releases/download/v0.1.0/kink_0.1.0_Darwin-x86_64.tar.gz"
      sha256 "00852e3640031be61b77f1a207e586250f00d77f505581a9c76d5fe4c0313679"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Trendyol/kink/releases/download/v0.1.0/kink_0.1.0_Linux-x86_64.tar.gz"
      sha256 "6dd0b694e6a7f2c3ac610609bdaba00ec96cd57c2139d111b341a060dfc8d178"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "kink"
  end

  test do
    system "#{bin}/kink version"
  end
end
