# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kink < Formula
  desc "KinK is a helper CLI that facilitates to manage KinD clusters as Kubernetes pods. Designed to ease clusters up for fast testing with batteries included in mind."
  homepage "https://github.com/trendyol"
  version "0.1.1"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Trendyol/kink/releases/download/0.1.1/kink_0.1.1_Darwin-x86_64.tar.gz"
      sha256 "33352e218ad9929f42ba16ad3aa30e393a6a1bee606c7606a9d945560304d2ac"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Trendyol/kink/releases/download/0.1.1/kink_0.1.1_Linux-x86_64.tar.gz"
      sha256 "94287d55edb75bc0e08cfbdf5bc0792c31b3d19b35f71e1ceb057d5e356f3f3e"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "kink"
  end

  test do
    system "#{bin}/kink version"
  end
end
